force-app/main/default/objects/AsyncRetryableTask__c/AsyncRetryableTask__c.object-meta.xml
<CustomObject>
    <label>Async Retryable Task</label>
    <nameField>
        <displayFormat>ART-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Retryable Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-async-retryable-tasks/force-app/main/default/objects/AsyncRetryableTask__c/fields/ApexJobId__c.field-meta.xml
<CustomField>
    <fullName>ApexJobId__c</fullName>
    <description>The async queueable job Id</description>
    <label>Apex Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncRetryableTask__c/fields/Attempts__c.field-meta.xml
<CustomField>
    <fullName>Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Attempts</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncRetryableTask__c/fields/ExecutionStartDatetime__c.field-meta.xml
<CustomField>
    <fullName>ExecutionStartDatetime__c</fullName>
    <description>When this task started its execution</description>
    <label>Execution Start Datetime</label>
    <type>DateTime</type>
</CustomField>

apex-async-retryable-tasks/force-app/main/default/objects/AsyncRetryableTask__c/fields/MaxRetries__c.field-meta.xml
<CustomField>
    <fullName>MaxRetries__c</fullName>
    <description>The maximum number of retries for this task</description>
    <label>Max Retries</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncRetryableTask__c/fields/SerializedParameters__c.field-meta.xml
<CustomField>
    <fullName>SerializedParameters__c</fullName>
    <description>Task parameters serialized as JSON object</description>
    <label>Serialized Parameters</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

apex-async-retryable-tasks/force-app/main/default/objects/AsyncRetryableTask__c/fields/TaskClassName__c.field-meta.xml
<CustomField>
    <fullName>TaskClassName__c</fullName>
    <description>The concrete class implementing this task</description>
    <label>Task Class Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

apex-async-retryable-tasks/force-app/main/default/objects/AsyncRetryableTask__c/fields/TaskConfigDeveloperName__c.field-meta.xml
<CustomField>
    <fullName>TaskConfigDeveloperName__c</fullName>
    <description>The Configuration CMDT Developer Name</description>
    <label>Task Config Developer Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

apex-async-retryable-tasks/force-app/main/default/objects/AsyncRetryableTaskConfiguration__mdt/AsyncRetryableTaskConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Configurations for Async Retryable Tasks</description>
    <label>Async Retryable Task Configuration</label>
    <pluralLabel>Async Retryable Task Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/AsyncRetryableTaskConfiguration__mdt/fields/MaxRetries__c.field-meta.xml
<CustomField>
    <fullName>MaxRetries__c</fullName>
    <description>Maximum number of retries</description>
    <label>Max Retries</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncRetryableTaskConfiguration__mdt/fields/TaskClassName__c.field-meta.xml
<CustomField>
    <fullName>TaskClassName__c</fullName>
    <label>Task Class Name</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

apex-async-retryable-tasks/force-app/main/default/objects/AsyncRetryableTaskLog__c/AsyncRetryableTaskLog__c.object-meta.xml
<CustomObject>
    <description>Log object for Async Retryable Tasks</description>
    <label>Async Retryable Task Log</label>
    <nameField>
        <displayFormat>ARTL-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Retryable Task Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-async-retryable-tasks/force-app/main/default/objects/AsyncRetryableTaskLog__c/fields/AsyncRetryableTask__c.field-meta.xml
<CustomField>
    <fullName>AsyncRetryableTask__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Async Retryable Task</description>
    <label>Async Retryable Task</label>
    <referenceTo>AsyncRetryableTask__c</referenceTo>
    <relationshipLabel>Async Retryable Task Logs</relationshipLabel>
    <relationshipName>AsyncRetryableTaskLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AsyncRetryableTaskLog__c/fields/Attempt__c.field-meta.xml
<CustomField>
    <fullName>Attempt__c</fullName>
    <label>Attempt</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncRetryableTaskLog__c/fields/LogMessage__c.field-meta.xml
<CustomField>
    <fullName>LogMessage__c</fullName>
    <label>Log Message</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

apex-async-retryable-tasks/force-app/main/default/objects/AsyncRetryableTaskLog__c/fields/SerializedTaskRecord__c.field-meta.xml
<CustomField>
    <fullName>SerializedTaskRecord__c</fullName>
    <label>Serialized Task Record</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AsyncRetryableTaskManager.cls
public with sharing class AsyncRetryableTaskManager {
    //
    //

    /**
     * 1. Create and returns a task instance of the configured value in
     * 'AsyncRetryableTaskConfiguration__mdt.TaskClassName__c' field.
     * 2. If the class cannot be found, a AsyncRetryableTaskException exception will be thrown.
     * 3. If the calculated idempotency key is already existent in any persisted record,
     *    a AsyncRetryableTaskException exception will be thrown.
     * 4. Persist a new AsyncRetryableTask__c record for holding the task status.
     * 5. Log the task creation.
     */
    public static AbstractAsyncRetryableTask createTask(
        AsyncRetryableTaskConfiguration__mdt taskConfig,
        Map<String, Object> parameters
    ) {
        AbstractAsyncRetryableTask concreteTaskInstance;

        // 1. Dinamically instantiate the concrete AbstractAsyncRetryableTask class.
        try {
            Type t = Type.forName(taskConfig.TaskClassName__c);
            concreteTaskInstance = (AbstractAsyncRetryableTask) t.newInstance();
            concreteTaskInstance.parameters = parameters;
            concreteTaskInstance.config = taskConfig;
        } catch (Exception ex) {
            throw new AsyncRetryableTaskException(
                'Error creating class instance for' + taskConfig.TaskClassName__c + ': ' + ex.getMessage()
            );
        }

        // 2. Get the idempotency key in the concrete class.
        // Each concrete class must have its implementation.
        String idempotencyKey = concreteTaskInstance.getIdempotencyKey();

        // 3. Idempotency Lock:
        // Verifies and blocks if there is an identical task key enqueued or executing.
        // If so, log it properly and abort the proccess.
        Boolean idempotencyCheckFailed = idempotencyKeyExists(idempotencyKey);
        if (idempotencyCheckFailed) {
            throw new AsyncRetryableTaskException('Task idempotency check hit. This task is already in execution.');
        }

        //4. Persists a new record for the concrete task
        AsyncRetryableTask__c taskRecord = createRecord(taskConfig, idempotencyKey, concreteTaskInstance);
        concreteTaskInstance.taskRecord = taskRecord;

        // 5. Log task creation
        createLog(taskRecord, AbstractAsyncRetryableTask.STATUS_CREATED, 'Task created.');
        return concreteTaskInstance;
    }

    /**
     * 1. Increment the number of attempts and updates the record.
     * 2. Enqueue the task with no delay (0), when it is the first attempt.
     * 3. Enqueue the task with apex system min. default queueable delay,
     *    when no delay parameter is given on the method call.
     *    > Setup > Apex Settings > Default minimum apex queueable delay (in seconds)
     */
    public static void enqueueTask(AbstractAsyncRetryableTask concreteTaskInstance) {
        if (concreteTaskInstance.taskRecord.Attempts__c == 0) {
            // TODO: check system governor limits before enqueueing!!!
            concreteTaskInstance.taskRecord.Attempts__c = 1;
            concreteTaskInstance.taskRecord.Status__c = AbstractAsyncRetryableTask.STATUS_EXECUTING;

            concreteTaskInstance.taskRecord.ApexJobId__c = System.enqueueJob(concreteTaskInstance, 0);
            update concreteTaskInstance.taskRecord;

            createLog(
                concreteTaskInstance.taskRecord,
                AbstractAsyncRetryableTask.STATUS_EXECUTING,
                'Task has been enqueued for the first time.'
            );
        } else {
            // TODO: check system governor limits before enqueueing!!!
            concreteTaskInstance.taskRecord.Attempts__c += 1;
            concreteTaskInstance.taskRecord.ApexJobId__c = System.enqueueJob(concreteTaskInstance);
            update concreteTaskInstance.taskRecord;
            createLog(
                concreteTaskInstance.taskRecord,
                AbstractAsyncRetryableTask.STATUS_RETRY,
                'Task enqueued for retry. Attempt no. ' + concreteTaskInstance.taskRecord.Attempts__c
            );
        }
    }

    /**
     * Verify if amount of retries has already reached the limit.
     * - If not: logs the error and enqueues the task again.
     * - Otherwise: logs the final step and finalizes the task.
     *              Task finalization is implemented by the concrete class.
     *
     */
    public static void handleRetry(AbstractAsyncRetryableTask concreteTaskInstance, String errorMessage) {
        AsyncRetryableTask__c taskRecord = concreteTaskInstance.taskRecord;

        Boolean isRetryableError = ErrorTypeEvaluator.evaluateErrorType(errorMessage);
        if (!isRetryableError) {
            concreteTaskInstance.taskRecord.Status__c = AbstractAsyncRetryableTask.STATUS_FINISHED_FAIL;
            concreteTaskInstance.finalizeTask(AbstractAsyncRetryableTask.STATUS_FINISHED_FAIL);
            createLog(
                concreteTaskInstance.taskRecord,
                AbstractAsyncRetryableTask.STATUS_FINISHED_FAIL,
                'Task aborted immediately. Non-retryable error encountered:\n' + errorMessage
            );
            return;
        }

        if (taskRecord.Attempts__c < taskRecord.MaxRetries__c + 1) {
            String logMsg = 'Execution failed. Scheduling retry... \nReason:\n' + errorMessage;
            createLog(taskRecord, AbstractAsyncRetryableTask.STATUS_ERROR, logMsg);
            enqueueTask(concreteTaskInstance);
        } else {
            // Max retries exhausted
            concreteTaskInstance.finalizeTask(AbstractAsyncRetryableTask.STATUS_FINISHED_FAIL);
            String logMsg = 'Task permanently failed. Max retry threshold reached.\nReason:\n' + errorMessage;
            createLog(taskRecord, AbstractAsyncRetryableTask.STATUS_FINISHED_FAIL, logMsg);
        }
    }

    /**
     * Create a log record and a debug output.
     * The logging procedure could also be plsced in the concerete task.
     * Following KISS principle, we do it here.
     */
    public static void createLog(AsyncRetryableTask__c taskRecord, String status, String message) {
        AsyncRetryableTaskLog__c log = new AsyncRetryableTaskLog__c();
        log.AsyncRetryableTask__c = taskRecord.Id;
        log.LogMessage__c = message != null && message.length() > 4096 ? message.substring(0, 4092) + '...' : message;
        log.Status__c = status;
        log.Attempt__c = taskRecord.Attempts__c;
        log.SerializedTaskRecord__c = JSON.serializePretty(taskRecord);
        insert log;
        System.debug(LoggingLevel.DEBUG, message);
    }

    /**
     * Check if the idempotency key is present among the executing records.
     */
    @TestVisible
    private static Boolean idempotencyKeyExists(String idempotencyKey) {
        List<AsyncRetryableTask__c> existingTasks = [
            SELECT Id, Status__c
            FROM AsyncRetryableTask__c
            WHERE
                IdempotencyKey__c = :idempotencyKey
                AND (Status__c = :AbstractAsyncRetryableTask.STATUS_CREATED
                OR Status__c = :AbstractAsyncRetryableTask.STATUS_EXECUTING)
            LIMIT 1
            FOR UPDATE
        ];
        return !existingTasks.isEmpty();
    }

    @TestVisible
    private static AsyncRetryableTask__c createRecord(
        AsyncRetryableTaskConfiguration__mdt config,
        String idempotencyKey,
        AbstractAsyncRetryableTask concreteTaskInstance
    ) {
        AsyncRetryableTask__c taskRecord = new AsyncRetryableTask__c();
        taskRecord.MaxRetries__c = config.MaxRetries__c;
        taskRecord.Attempts__c = 0;
        taskRecord.Status__c = AbstractAsyncRetryableTask.STATUS_CREATED;
        taskRecord.TaskClassName__c = config.TaskClassName__c;
        taskRecord.IdempotencyKey__c = idempotencyKey;
        taskRecord.ExecutionStartDateTime__c = Datetime.now();
        taskRecord.SerializedParameters__c = JSON.serialize(concreteTaskInstance.parameters);
        taskRecord.TaskConfigDeveloperName__c = config.DeveloperName;
        insert taskRecord;
        return taskRecord;
    }
}