force-app/main/default/objects/AsyncRetryableTask__c/AsyncRetryableTask__c.object-meta.xml
<CustomObject>
    <label>Async Retryable Task</label>
    <nameField>
        <displayFormat>ART-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Retryable Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncRetryableTask__c/fields/ExecutionEndDatetime__c.field-meta.xml
<CustomField>
    <fullName>ExecutionEndDatetime__c</fullName>
    <description>When this task has ended its executed (after all retries)</description>
    <label>Execution End Datetime</label>
    <type>DateTime</type>
</CustomField>

apex-async-retryable-tasks/force-app/main/default/objects/AsyncRetryableTaskConfiguration__mdt/AsyncRetryableTaskConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Configurations for Async Retryable Tasks</description>
    <label>Async Retryable Task Configuration</label>
    <pluralLabel>Async Retryable Task Configurations</pluralLabel>
</CustomObject>

apex-async-retryable-tasks/force-app/main/default/classes/AbstractAsyncRetryableTask.cls
public abstract class AbstractAsyncRetryableTask implements Queueable, Database.AllowsCallouts {
    //
    //
    public static final String STATUS_EXECUTING = 'Executing';
    public static final String STATUS_CREATED = 'Created';
    public static final String STATUS_FINISHED_FAIL = 'Finished with Fail';
    public static final String STATUS_FINISHED_SUCCESS = 'Finished with Success';
    public static final String STATUS_RETRY = 'Retry';
    public static final String STATUS_ERROR = 'Error';

    public Map<String, Object> parameters { get; set; }
    public String configDeveloperName { get; set; }
    public AsyncRetryableTask__c taskRecord { get; set; }
    public AsyncRetryableTaskConfiguration__mdt config { get; set; }

    public AbstractAsyncRetryableTask() {
    }

    public abstract void process();

    public abstract String getIdempotencyKey();

    /**
     * The execute() method will call the process() method in the concrete class.
     * The concrete class must implement a selective retry mechanism, depending on the error type.
     * For triggering a retry, it shall call handleFailure().
     */
    public void execute(QueueableContext context) {
        process();
    }

    /**
     * Delegates the error to the Task Manager for handling the failure
     * Check first if a retry really makes sense
     */
    public void handleError(Exception ex) {
        AsyncRetryableTaskManager.handleRetry(this, ex.getMessage());
    }

    public void finalizeTask(String status) {
        taskRecord.Status__c = status;
        taskRecord.ExecutionEndDatetime__c = Datetime.now();
        update taskRecord;
        AsyncRetryableTaskManager.createLog(taskRecord, status, 'Task finished with status: ' + status);
    }
}